pipeline {
  agent any
  environment {
    AWS_ACCOUNT_ID='975050170292'; AWS_REGION='ap-southeast-1'
    ECR_REGISTRY="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
    ECR_REPO='rmit-store-frontend'
  }
  stages {
    stage('Checkout'){ steps {
      checkout scm; script { env.TAG = sh(returnStdout:true, script:'git rev-parse --short HEAD').trim()+"-${env.BUILD_NUMBER}" }
    }}
    stage('ECR Login'){ steps { sh 'aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY' } }
    stage('Ensure Repo'){ steps { sh 'aws ecr describe-repositories --repository-names $ECR_REPO --region $AWS_REGION || aws ecr create-repository --repository-name $ECR_REPO --region $AWS_REGION' } }
    stage('Build'){ steps { sh 'docker build -t $ECR_REPO:$TAG -f frontend/Dockerfile frontend' } }
    stage('Push'){ steps { sh 'docker tag $ECR_REPO:$TAG $ECR_REGISTRY/$ECR_REPO:$TAG && docker push $ECR_REGISTRY/$ECR_REPO:$TAG' } }
  }
}
